### PR TITLE
ParameterMetaDataBackup: update

### PR DESCRIPTION
**Pull request by floaledm**
Serial parameter update to include latest protocol (FrSky SPort Passthrough) and name fixes for FrSky D and FrSky SPort protocols (see https://github.com/ArduPilot/ardupilot/pull/3434).

### CODE REVIEW

**Comment by meee1** [comment]
has the code that the xml file is based off been updated? in ArduPilot?

**Comment by floaledm** [comment]
Hi Michael,

The code is in ArduPilot master and Copter-3.4-rc3 branches. Trisge is the one who merged...

**Comment by meee1** [comment]
@floaledm the reason I havnt pulled this is the "backup" I always leave at the stable firmware level, I would suggest updating to beta MP in your case, as it will gather the latest xml file during the upgrade to beta.

**Comment by floaledm** [comment]
@meee1 Where is the beta MP file I should change? Thanks.

**Comment by meee1** [comment]
its auto generated on update.

**Comment by floaledm** [comment]
So, is there anything I should change or is it a matter of waiting for Copter-3.4 stable?

**Comment by meee1** [comment]
waiting for release, indeed.
but if you do a beta update in MP it will autogenerate the new file with the missing info.

**Comment by floaledm** [comment]
Sounds good. Just curious, what's the source of the autogenerated file? Where is it getting the info from?

**Comment by meee1** [comment]
for stable the  *.stable tag in GitHub.
for beta master in github

**Pull request closed without merging**
