### PR TITLE
Do not display waypoints with lat and lon 0

### PR DESCRIPTION
**Pull request by tatsuy**
I often set the lat=0 and lon=0 of waypoint to hold the current location.
but I am not happy that the location of (0, 0) is displayed on the map.

Before
image

After
image

### CODE REVIEW

**Comment by meee1** [comment]
I don't actually like this approach, as it hides a possible user problem. I think the user should be shown an error such as this. Hiding it archives nothing.

**Comment by tatsuy** [comment]
What is a possible user problem?
ArduPilot supports  to hold the current position using WAYPOINT command.
> Lat, Lon - the latitude and longitude targets. If left as zero it will hold the current location.
https://ardupilot.org/copter/docs/mission-command-list.html#waypoint

**Comment by rmackay9** [comment]
In the flight code, the lat/lon of 0,0 is interpreted as stay-at-current-location so I think it makes sense not to show the line back to the west side of Africa.

**Comment by meee1** [comment]
@rmackay9 are you aware if that applys to all codebases?

**Comment by rmackay9** [comment]
@meee1,

It's certainly true of Copter and Plane.  [Here's the code for Plane](https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/commands.cpp#L31).  I'll check Rover but even if it's not we should make it the same as Copter and Plane.

**Comment by rmackay9** [comment]
@meee1 great, txs!

**Comment by tatsuy** [comment]
@meee1 , @rmackay9 
Thank you for the review and merging.

**Pull request merged**
