### PR TITLE
Extra variables in currenstate for plugin use.

### PR DESCRIPTION
**Pull request by EosBandi**
Currently it is very hard (if not impossible) to add variables to current state from a plugin (cannot display anything in QuickView tab). This PR adds five cs variables (extra1..5) and the possibility to add description to them from settings. (<extra1_desc> etc...) Since these variables are not binding to a datasource they can be directly manipulated from a plugin.

### CODE REVIEW

**Comment by EosBandi** [comment]
@meee1 Any thoughts on this ?

**Comment by magicrub** [comment]
LGTM. Would it be worthwhile to make it a double instead of a float?

**Comment by EosBandi** [comment]
The main reason for these variables is to proved means for displaying values on the QuickView tab and on the HUD. I don't see any use case where double precision is needed....

**Comment by meee1** [comment]
ok the reason for the delay, is i think this
https://github.com/ArduPilot/MissionPlanner/issues/2346
could be tied into this as well

**Comment by EosBandi** [comment]
Reimplemented in https://github.com/ArduPilot/MissionPlanner/pull/2360

**Pull request closed without merging**
