### PR TITLE
ADSB: Add transponder control for ping200x support

### PR DESCRIPTION
**Pull request by nicholas-inocencio**
Codependent with https://github.com/ArduPilot/ardupilot/pull/18637 and requires https://github.com/ArduPilot/mavlink/pull/225.

Adds a Transponder tab with controls for the following ADS-B fields, for use with a ping200x. 
- FlightID
- Squawk
- NIC
- NACp
- STBY/ON/ALT
- IDENT
Additionally, adds indicators for the following:
- Maintenance required
- GPS Unavailable
- GPS No Fix
- Transponder System Failure
- On Ground

### CODE REVIEW

**Comment by meee1** [comment]
Looks nice and clean. thanks!

**Comment by nicholas-inocencio** [comment]
I may have to amend some mavlink stuff here due to upstream changes to the uavionix.xml that I missed.

**Comment by meee1** [comment]
let me know when you think your done..  ill let it settle a little while before i merge

**Comment by nicholas-inocencio** [comment]
Will do.

**Comment by nicholas-inocencio** [comment]
I've finished making changes, assuming edits to ArduPilot/ardupilot#18637 and ArduPilot/mavlink#225 don't cause any changes on this end.

**Comment by magicrub** [comment]
@nicholas-inocencio looks like there's a merge conflict on here blocking it's merge. Can you take a look?

**Comment by nicholas-inocencio** [comment]
@magicrub Should be cleared now.

**Pull request merged**
