### PR TITLE
fir for heli stable/dev SITL selection ISSUE #2733

### PR DESCRIPTION
**Pull request by EosBandi**
fix for ISSUE #2733

### CODE REVIEW

**Comment by meee1** [comment]
merge conflict, can you rebase?

**Comment by EosBandi** [comment]
Sure, sorry it should have been done on the same branch as the other fix, not in master.

**Comment by meee1** [comment]
i dont think that helped.

the best way is to do a git rebase on master, this will re commit just the patch in question ontop of master

**Comment by EosBandi** [comment]
I messed up, closing this and redo the fix in a new PR.
(Sorry still in the low side of Git learning curve)

**Pull request closed without merging**
