### PR TITLE
Udp multicast

### PR DESCRIPTION
**Pull request by jfint**
Added a multicast UDP join prompt to UDP communications, and added some values to the rate pull-downs.  I had intended to do these as 2 pull requests, but having some issue doing that with the pull request interface.

### CODE REVIEW

**Comment by meee1** [comment]
current beta MP already support multicast.

use UDPCL, and enter a multicast ip and port. and it will connect.

**Comment by jfint** [comment]
Oh great, will that be in the 1.3.71 release?

**Comment by jfint** [comment]
Also, I just checked the Beta update, it does not seem to join the multicast group.

**Comment by meee1** [comment]
What milticasy address are you using?

**Comment by jfint** [comment]
224.1.0.44:51019

**Comment by jfint** [comment]
I see, you are only allowing 239.x.x.x or 224.0.0.x

**Comment by meee1** [comment]
yep, thats the defaults for sitl ie 239.255.145.50
should really be a range however

**Comment by jfint** [comment]
I'm going to close this request, and possibly try again by opening that up.

**Comment by jfint** [comment]
Thank you

**Comment by jfint** [comment]
@meee1 I wanted to ask here before doing anything else.  The multicast behavior on UDPCL is to send uplink data on the IP and port that is entered, this is generally bad behavior for multicast using the same IP and port for both directions.  The behavior on UDP was to unicast up with Multicast listening, and to uplink on the recievePort+1.  So if Mission planner listened to port 14550, it uplinked on port 14551.  In general this is better behavior.  I think if it multicasted uplink, but on a different port that would at least allow application layer filtering to shelter things from unwanted data.

Do you have any opinions on how you would like it implemented if the IP entered on UDPCL is multicast?

**Pull request closed without merging**
