### PR TITLE
Added checkbox "Skip Download"

### PR DESCRIPTION
**Pull request by roberthudson**
As per Tridge's request to skip downloading of SITL binaries

https://github.com/ArduPilot/MissionPlanner/issues/2518

(also adjusted tab order of controls)

### CODE REVIEW

**Comment by tridge** [comment]
I've tested this and it works nicely. It looks like this:
image
if the SITL binary doesn't exist you get a popup saying that it failed to download

**Comment by roberthudson** [comment]
I wasn't sure where to put the checkbox.

Placing it to the right of "Wipe" would mean widening the control. That might have negative consequences on narrower screens.

Feel free to adjust as you see fit.

**Comment by roberthudson** [comment]
Instead of a checkbox, would it be better to simply skip downloading if the binary already exists?

Or is it important to download the latest version? How often do the binaries change?

Sorry for the questions, I'm new here :-)

**Comment by tridge** [comment]
> Or is it important to download the latest version? How often do the binaries change?

they change whenever ArduPilot master changes, which is often several times in a day. We usually do want the latest build, but in the future we might like an option to download one of the stable builds.

**Pull request merged**
