### PR TITLE
Add new board NXP RDDRONE-FMUK66

### PR DESCRIPTION
**Pull request by jarivanewijk**
Added support for the NXP RDDRONE-FMUK66, more info: #2149 

I'm not very familiar with the MissionPlanner source, so please have a look if I made the right changes and generated and signed the .cat file correctly.

The main goal is to have driver support for now. Detection and firmware update in Mission Planner would be nice, but there is only PX4 support right now (not Ardupilot yet).

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@meee1 I've lost track of where you are dropping the built version of px4driver.msi. Could you point me to that again. Sorry about that. I'll add some docs for where it comes from to QGC.

**Comment by magicrub** [comment]
Adding support for new hardware is trivial with our chibiOS infrastructure. Has anyone thrown together a hwdef yet?

**Comment by jarivanewijk** [comment]
@magicrub Are you referring to these steps to port ArduPilot onto a new flight controller? http://ardupilot.org/dev/docs/porting.html

It might not be a trivial task because we are using a NXP Kinetis K66, not a STM32F4 or STM32F7. 
I am not sure if there are any current plans within NXP to start porting ArduPilot onto the RDDRONE-FMUK66, but maybe in the future we will pick that up again. I am not in a position to decide.

For our current needs, driver support and detection within Mission Planner should be enough. As far as I'm aware, that's working now.

**Comment by magicrub** [comment]
Ahh yes, my bad. The script architecture is for stm32s.

**Comment by DonLakeFlyer** [comment]
Ok, I did some poking and I think the pre-built driver.msi comes from here: http://firmware.ardupilot.org/Tools/MissionPlanner/driver.msi

If that is correct then:
- The drivers.wxs file was not updated in this pull so the drivers.msi does not include this new driver.
- The name of the install for this is "Drivers" which is not super helpful for users to understand what this is. It shows up as "Drivers" for example in the uninstall list. Can it be changed to something more descriptive. It used to be "PX4 Drivers" which was more useful. Can it be changed to something like "AutoPilot Drivers" or "UAV AutoPilot Drivers" or something like that.

I'm also not sure any more how to detect somehow from the registry whether the latest version of this is installed? It seems like the version is 1.3.7 but that doesn't seem to be updated ever. Is there some other reg keys I can check to determine whether a new version of drivers needs to be installed?

**Comment by dk7xe** [comment]
@DonLakeFlyer @magicrub please give feedback what needs to be done and by who'm to have the driver finally updated.
Thank you, Gerald

**Comment by meee1** [comment]
drivers are available here
http://firmware.ardupilot.org/Tools/MissionPlanner/driver.msi

**Comment by meee1** [comment]
@DonLakeFlyer i think most of your concern have been addressed. the msi uses the same upgrade code as the old package, so should inplace upgrade without any issues.
and is now UAV Driver

**Comment by DonLakeFlyer** [comment]
> i think most of your concern have been addressed.

Thanks so much @meee1. I'll pull in the new version to QGC setups.

**Comment by dk7xe** [comment]
BTW, i have tested the driver on a fresh win10 Installation yesterday by copying the driver folder from git over into the driver folder QGC has generated. FMUK66 is perfectly recognized.

**Comment by DonLakeFlyer** [comment]
@meee1 I put the new drivers into QGC install. But the problem is that I don't see how I can decide whether the driver package needs to be run or not. If I run the package when it already installed then the user gets the "Repair/Remove" variation of setup which is confusing. I don't think I can leave it that way because lots of folks won't know what to do or think something has gone wrong. Is there some way I check whether the drivers are already up to date with the version I have in the QGC installer?

**Pull request merged**
