### PR TITLE
Mcast dronecan

### PR DESCRIPTION
**Pull request by meee1**

### CODE REVIEW

**Comment by rmackay9** [comment]
I wonder if maybe this has broken the ability to see DroneCAN messages from connected DroneCAN devices?  For example, I'm trying to see DroneCAN parameters from a Xacti gimbal and it doesn't show up.  Only mission planner shows up
image

**Comment by robertlong13** [comment]
Just to close the loop on this, this is an ArduPilot bug https://github.com/ArduPilot/ardupilot/issues/28175

However, as I was testing this out, I did notice there's no way to disconnect the MAVLinkCAN or switch from 1 to 2 without disconnecting the autopilot. Or am I missing something?

**Comment by meee1** [comment]
Did switching tabs work? Used to?

**Comment by robertlong13** [comment]
> Did switching tabs work? Used to?

Ah, switching tabs works. I had only tried switching to other backstage views.

**Pull request merged**
