### PR TITLE
OnboardOSD Config tool impl.

### PR DESCRIPTION
**Pull request by SergeyBokhantsev**
This is a config tool for Ardupilot's Onboard OSD.
Now it is only supports online mode (need a connection to a FC). Next step is to implement offline mode (edit .params file).
Conceptually it is designed to generically support any new OSD  items/parameters that could be added later to Ardupilot without need to make a changes to config tool.
Items selecting/positioning by a mouse is supported.

image

image

### CODE REVIEW

**Comment by tridge** [comment]
great stuff, thanks!

**Comment by vierfuffzig** [comment]
awesome!

**Comment by sh83** [comment]
Thanks you! Ardupilot OSD should be much more usable with this tool.

**Comment by tridge** [comment]
I've tested this and it works very well
the only issue I hit is that if you enable a screen that wasn't previously enabled then you need to disconnect and reconnect to see it
hmm, one more thing, the "Onboard OSD" option appears even if the board has no OSD parameters. I think it shouldn't show in the side-bar in that case

**Comment by SergeyBokhantsev** [comment]
@tridge thanks,
>>the only issue I hit is that if you enable a screen that wasn't previously enabled then you need to disconnect and reconnect to see it

this because the GUI is dynamically generated basing on the OSD setting the Ardupilot provided to MP. For disabled screens there are no settings so you need to refresh your settings after screen was enabled.
Now there are no explicit [Refresh] button (but you could switch to Parameters list and do refresh from there). Anyway this may be improved by showing a message box after user had enabled a screen: "Do you want to refresh now? Y/N" 

>> the "Onboard OSD" option appears even if the board has no OSD parameters

The MP layout is created before a connection, so maybe @meee1 will advice here, because I didn't found an appropriate hook that could show/hide sidebar items after a connection and parameters receive completion.
As an option could be the MP configuration setting "Show Onboard OSD Configurator"

**Comment by meee1** [comment]
have a look at using IActivate. use this to regenerate the screen

**Comment by SergeyBokhantsev** [comment]
@meee1 yes, I'm using IActivate, no problems here. The question is there a way to dynamically hide or show OnboardOSD item form here, basing on absence or presence of OSD_... settings:
image

**Comment by knputyi** [comment]
Just tested a bit, working like a charm ! Love it !
capture

**Comment by SergeyBokhantsev** [comment]
thanks, @knputyi 
from your screenshot it seems I definitely need to add a scaling option to allow user to make OSD screen 2x smaller. For smaller monitors.

**Comment by knputyi** [comment]
> 
> 
> thanks, @knputyi
> from your screenshot it seems I definitely need to add a scaling option to allow user to make OSD screen 2x smaller. For smaller monitors.

Haha, I need reading glasses, for me, bigger is better !

**Comment by SergeyBokhantsev** [comment]
Ok, then I need to add a scrollbars to the whole tool window. Because currently I don't understand how can you access the OSD Items panel that is below OSD screen.

**Comment by SergeyBokhantsev** [comment]
>>  I accesed the OSD settings in the Parameter list, or tree!
Good workaround, but that is not how I planned the usability :)

**Comment by knputyi** [comment]
I shared the upcoming great news on 2 different FB pages, a LOT of positive feedback in a few hours ! Keep up the good work, waiting for devs to merge it in master.

**Comment by SergeyBokhantsev** [comment]
@meee1 I believe this is near from feature-complete now, please review.
image
image

**Comment by knputyi** [comment]
Ok, nice job again !
One issue : as seeing on first pic., some part from the right side of the window is missing.
Improvement could be made by adding a scroll bar , as I marked with green on second pic.

osd1
osd2

**Comment by knputyi** [comment]
Hi.
Is in Master already ?

**Comment by SergeyBokhantsev** [comment]
Not yet, waiting @meee1 for a review.
Also I will fix your note about scroll bar.

**Comment by knputyi** [comment]
Thanks. It is an outstanding work!
Best regards, Norbert

**Comment by knputyi** [comment]
So, is this project stuck somewhere?

**Comment by amagr0** [comment]
Hello,
I already have FPV+OSD connected to Pixhawk, but I don't see the "Onboard OSD" page in "Config/Tuning". 
Is it necessary to do any activation in order to access to the "Onboard OSD" page ?

Thanks

**Pull request merged**
