### PR TITLE
Add interface for plugins to add HW and SW config pages

### PR DESCRIPTION
**Pull request by EosBandi**
It makes possible for a plugin to add pages to the SETUP and the CONFIG pages.

 Simply create a MyUserControl based form and then add it via
` SoftwareConfig.AddPluginViewPage(typeof(pageclass), "pagename");`
or 
` InitialSetup.AddPluginViewPage(typeof(pageclass, "pagename");`

### CODE REVIEW

**Review by robertlong13 — APPROVED** [review]
This is great. Been wanting something like this for a while.

**Comment by robertlong13** [comment]
Do you have a minimal example plugin for this? I could whip one up if you don't.

**Comment by EosBandi** [comment]
How we shall distribute these examples ? It won't work as a single file .cs since it needs a form...

**Comment by meee1** [comment]
Check generator.cs. Definitely doable

**Comment by EosBandi** [comment]
:) Ok put together a small example.

**Pull request merged**
