### PR TITLE
Setup: SerialPort settings screen

### PR DESCRIPTION
**Pull request by EosBandi**
Collects all information about serial ports on a single screen. Using rules defined in the SerialOptionRules.json to add comments and set mandatory options/baudrate when a certain protocol selected.

### CODE REVIEW

**Comment by rmackay9** [comment]
This sounds like a good idea, thanks!

**Comment by meee1** [comment]
can i request a screenshot?

**Comment by EosBandi** [comment]
Sorry, sure. 
image

**Comment by rmackay9** [comment]
I'm not an official reviewer of MP PRs of course but where does the 2nd line, "UART2", etc come from?

I wonder if we could add the BRD_SER1/2_RTSCTS params alongside SERIAL1 and SERIAL2.

**Comment by rmackay9** [comment]
I'd also use "baud" instead of "speed".  I know that "speed" is perhaps more understandable to the lay user but we should try and avoid synonyms I think.

**Comment by rmackay9** [comment]
Sorry for the drip-feed of suggestions.. but just one more, in terms of where it appears in the "Mandatory Hardware" section, I'd probably say it should go lower in the list... perhaps just below "Servo Output".

**Comment by EosBandi** [comment]
> I'm not an official reviewer of MP PRs of course but where does the 2nd line, "UART2", etc come from?
> 
> I wonder if we could add the BRD_SER1/2_RTSCTS params alongside SERIAL1 and SERIAL2? This is scope creep though, so just a suggestion.

- UART numbers are coming from the @sys/uarts.txt (if available), an idea from Andy Piper.
- BRD_SER_RTSCTS can be added; let me take a look at it... (or keep it to the next version ?)
- It can go down, no problem,
- Speed and baud are used interchangeably in the documentation with a favor for the term speed instead of baud rate.

**Comment by EosBandi** [comment]
Moved tab down below Servo Outputs
Add checking and displaying BRD_SERx_RTSCTS settings
Make it a little less cluttered
image

**Pull request merged**
