### PR TITLE
Map: Added Japan Maps

### PR DESCRIPTION
**Pull request by muramura**
I would like to add a map of Japan.
· There are few plains in Japan.
· The height of the terrain is difficult to grasp on Google Maps.
· Make multi-copter fly in the mountains.
· Past images are not hidden like roads.
· You may use a submarine map on the ocean floor.

### CODE REVIEW

**Comment by meee1** [comment]
can I request a change to move the maps libs to MissionPlanner.Maps
and then inject into the instance in program.cs in MP
eg
 // add my custom map providers
            GMap.NET.MapProviders.GMapProviders.List.Add(Maps.WMSProvider.Instance);

**Comment by muramura** [comment]
@meee1 san. thank you for your comment.
I will change.

**Comment by meee1** [comment]
@muramura thanks just trying to minimise changes to the external lib aka gmaps

**Comment by muramura** [comment]
@meee1 san.. I want advice.
I changed it.
Up and down of the line of the map are reversed.
Where should I change and change?
now (NG)
4
3
2
1
before (OK view)
1
2
3
4
ddd

**Comment by meee1** [comment]
@muramura please have a look at Eniro_topo
            ret = string.Format(CultureInfo.InvariantCulture, CustomURL, zoom, pos.X, (1 << zoom) - 1 - pos.Y);
this does a Y axis reverse

**Pull request closed without merging**
