### PR TITLE
CoT: Add Cursor-on-Target output

### PR DESCRIPTION
**Pull request by magicrub**
This is a USA military GCS standard to visualize (and in some cases control) UAVs. This PR will add ability to forward a connected vehicle's data to a remote GCS. This is based on the NMEA output. Works the same way.

This is a WIP - some commits may need to be removed (for example, the "remove sub-projects" thing.

### CODE REVIEW

**Comment by magicrub** [comment]
This has been "flight tested" and works great. Just need to clean it up a bit

**Comment by meee1** [comment]
let me know when your ready

**Comment by magicrub** [comment]
I'll fix it up tomorrow

**Comment by magicrub** [comment]
ready!

**Pull request merged**
